# Generated by Django 3.1.4 on 2022-07-09 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_auto_20220709_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 7, 9, 11, 57, 42, 657682, tzinfo=utc), max_length=19),
        ),
    ]
