# Generated by Django 3.1.4 on 2022-07-16 10:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_auto_20220709_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 7, 16, 10, 21, 44, 485536, tzinfo=utc), max_length=19),
        ),
    ]
