# Generated by Django 3.1.4 on 2022-07-16 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_auto_20220716_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='detailed_desc',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 7, 16, 11, 3, 58, 362174, tzinfo=utc), max_length=19),
        ),
    ]
