# Generated by Django 3.1.14 on 2022-11-19 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_auto_20220716_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2022, 11, 19, 13, 16, 33, 41640, tzinfo=utc), max_length=19),
        ),
    ]
